Initial CP for unique identifier for association instance.
IHE/DEV.PCIM pull request #103
Opened 2024-05-09 18:53 UTC by eldonmetz

OBR-3 and OBR-29 usage similar to ACM PCD-[04,06 and 07].

Closes #99 

## 📑 Description
After PCIM connectathon testing in 2024, it was noted that it would simplify update logic for consumers if to the Device-Patient Association Manager (DPAM) assigned a unique identifier at the start of an association instance and referenced it for updates. This would also be consistent with ACM profile PCD-04, PCD-06 and PCD-07 transactions.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

## ℹ Additional Information

2024-05-09 20:48 UTC, engelbert65 requested changes

2024-05-09 20:48 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +After PCIM connectathon testing in 2024, it was noted that it would simplify update logic for consumers if to the Device-Patient Association Manager (DPAM) assigned a unique identifier at the start o
Typo:  "...for consumers **if to** the Device-Patient..." should be "...for consumers **if** the Device-Patient..."

2024-05-09 20:48 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +In the DEV-51 and DEV-52 transactions of the PCIM Profile, this field serves as the unique identifier for the initial association instance and each subsequent update to that association. This value i
Need to make it clear that OBR-3 from the initial association message goes in OBR-29.2 (Parent.Filler Assigned Identifier), and that the delimiter within OBR-3 changes from '^' to '&' when putting it in OBR-29.2.

Here's text from an ACM CP written 2 years ago (https://docs.google.com/document/d/185t8bjqTm9ZF4sSxp9aGYFFozc6orSLu/edit?pli=1):

"...a transcription of the OBR-3 component values to subcomponents while replacing the component delimiters (^) with subcomponent delimiters (&)"

2024-05-09 20:48 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +
Same as above, need to be clear that OBR-29.2 is the value of interest.

2024-05-09 20:48 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +| Unique instance identifier for the originating association event that all updates apply to. See Appendix B.7 OBR - Observation Request Segment OBR-29 Parent (EIP) 00261for additional details.
Typo:  add space after "00261".

2024-05-10 14:44 UTC, eldonmetz commented
@engelbert65 Changes made based on feedback. [HTML output here.](https://htmlpreview.github.io/?https://github.com/IHE/DEV.PCIM/blob/dd79aa9684578fedc2ebd16aa7c3e4de93d5aef7/CPs/in_progress/cp_nn6.html)

2024-05-10 14:48 UTC, eldonmetz commented
@engelbert65  Additional formatting changes. [HTML here.](https://htmlpreview.github.io/?https://github.com/IHE/DEV.PCIM/blob/f6999376051775afc6769dfa2a59a0d307c633d4/CPs/in_progress/cp_nn6.html)

2024-05-17 14:10 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +When transcribing the the components of the OBR-3 field value to the OBR-29.2, all subscomponents shall be transcribed and the component delimiters (^) replaced with subcomponent delimiters (&).
```suggestion
When transcribing the the components of the OBR-3 field value to OBR-29.2, all subcomponents shall be transcribed and the component delimiters (^) replaced with subcomponent delimiters (&).
```

2024-05-17 14:12 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +When transcribing the components of the OBR-3 field value to the OBR-29.2 all subcomponents shall be transcribed and the component delimiters (^) replaced with subcomponent delimiters (&).
```suggestion
When transcribing the components of the OBR-3 field value to OBR-29.2, all subcomponents shall be transcribed and the component delimiters (^) replaced with subcomponent delimiters (&).
```

2024-05-30 21:36 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +MSH|^~\&|MonitorGateway||AssocMgr||20160726160000||ORU^R01^ORU_R01|12d1574|P|2.6|||AL|AL|USA||||IHE_DEV_051^IHE PCD\^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
Remove the backslash after "IHE PCD"

2024-05-30 21:36 UTC, engelbert65 commented on asciidoc/cp_nn6.adoc
> +OBR|||15404697^^|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726160000|20160726160000
The "^^" in OBR-3 are not in the existing text.

2024-05-30 21:48 UTC, engelbert65 approved these changes

2024-09-03 22:46 UTC, merged