I12 proposed edits for day one f2f morning session
IHE/DEV.PCIM pull request #13
Opened 2023-05-23 19:36 UTC by reh-imt

Updated nn-6 asciidoc with changes proposed in the morning session of the May 23 Face-to-Face meeting in Alexandria VA.

2023-05-24 17:58 UTC, eldonmetz commented on CPs/cp_nn6.adoc
> +A Device-Patient Association Manager may filter association messages to a Device-Patient Association Consumer for the list of devices associated with particular patients at present. Retrospective que
add "and ongoing" after "at present".

2023-05-24 17:59 UTC, eldonmetz commented on CPs/cp_nn6.adoc
> +For status display or for error-checking and diagnostic purposes, the Device-Patient Association Manager sends the Device-Patient Association Consumer the present association records for each patient
Change "present" to "current".

2023-05-24 18:00 UTC, eldonmetz commented on CPs/cp_nn6.adoc
> +A Device-Patient Association Manager may filter association messages to a Device-Patient Association Consumer for the list of devices associated with particular patients at present. Retrospective que
Consider changing "present" to "current".

2023-05-24 18:01 UTC, eldonmetz commented on CPs/cp_nn6.adoc
> +The list of medical devices that can be associated with the patient may be preconfigured or automated with MEM DMC DMIR. Device registration may also be manually accomplished during system setup and
Remove "DMIR". Not needed, just reference profile.

2023-05-24 18:04 UTC, eldonmetz requested changes
Please modify per the review comments.

2023-05-25 13:08 UTC, eldonmetz commented
@bilhar97 and @TomKowal. I applied, committed and pushed the recommended changes. Probably easiest to review by focusing in and clicking on the changes related to my morning commits. @reh-imt, thanks for this initial push, I think we are close to merging this in.

2023-05-25 14:27 UTC, bilhar97 approved these changes
Reviewed latest changes to cp_nn6.adoc. I did not review HTML (except index.html) since it is generated from the adoc. Changes look good to me. Approved.

2023-05-25 14:37 UTC, eldonmetz commented
> Reviewed latest changes to cp_nn6.adoc. I did not review HTML (except index.html) since it is generated from the adoc. Changes look good to me. Approved.

Thanks, updated html and pushed that commit.

2023-05-25 14:37 UTC, merged